// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClpLXe0MdkZnZpBBMKYrBEwZdEUO1UUHw',
    appId: '1:974381490541:web:95c055fd095344e2817a64',
    messagingSenderId: '974381490541',
    projectId: 'stytore',
    authDomain: 'stytore.firebaseapp.com',
    storageBucket: 'stytore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDtlhAw0w_opMwU8ELa64RIUqgfjAxhrE',
    appId: '1:974381490541:android:b00a9b026bee15f8817a64',
    messagingSenderId: '974381490541',
    projectId: 'stytore',
    storageBucket: 'stytore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXGEdmfqeDYQjafpaibJoSaBgeFEYYuQ',
    appId: '1:974381490541:ios:14a58ab31d32f4c0817a64',
    messagingSenderId: '974381490541',
    projectId: 'stytore',
    storageBucket: 'stytore.appspot.com',
    iosClientId: '974381490541-k8709f7ijj84ppiaalh7hpqib5mv2tev.apps.googleusercontent.com',
    iosBundleId: 'com.example.stytore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtXGEdmfqeDYQjafpaibJoSaBgeFEYYuQ',
    appId: '1:974381490541:ios:bd3a5a93b9be0f6d817a64',
    messagingSenderId: '974381490541',
    projectId: 'stytore',
    storageBucket: 'stytore.appspot.com',
    iosClientId: '974381490541-hn0g04omtemfbi6vp4eumo2g024uharr.apps.googleusercontent.com',
    iosBundleId: 'com.example.stytore.RunnerTests',
  );
}
